// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6z8mNyg5fCp13vUOIoO85-OB8qvkt0U',
    appId: '1:1051080314093:web:9c3afff95a3c7e6dbf90e4',
    messagingSenderId: '1051080314093',
    projectId: 'ocr-ktm',
    authDomain: 'ocr-ktm.firebaseapp.com',
    storageBucket: 'ocr-ktm.appspot.com',
    measurementId: 'G-SH62HPSVTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtBL3hPz_81fT3qC7Hqo4yc7g-yjhOXgo',
    appId: '1:1051080314093:android:41d37ba6f98290d8bf90e4',
    messagingSenderId: '1051080314093',
    projectId: 'ocr-ktm',
    storageBucket: 'ocr-ktm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHCLrlJNyruw-IAGvmdSxu9Yprvr37xM',
    appId: '1:1051080314093:ios:e133ceb91e8bbbc5bf90e4',
    messagingSenderId: '1051080314093',
    projectId: 'ocr-ktm',
    storageBucket: 'ocr-ktm.appspot.com',
    iosBundleId: 'tubes.smt5.penilaian',
  );
}
